Repository NewFuture/custom-stickers-teams-extension, pull requests merged in 2022-09, with the labels that each got.

#96 fix manifest
  manifest/.env
  manifest/.env.development
  manifest/package.json
  manifest/stickers/manifest.json
  yarn.lock
Labels: Area:TeamsManifest

#97 init
  client-config-app/package.json
  client-config-app/src/App.tsx
  client-config-app/src/header/LanguageButton.tsx
  client-config-app/src/header/headerBtns.tsx
  client-config-app/src/lib/http.ts
  client-config-app/src/lib/store.ts
  client-config-app/src/list/UploadButton.tsx
  client-config-app/src/list/image-item.tsx
  client-config-app/src/list/image-list.tsx
  client-config-app/src/list/index.tsx
  client-config-app/src/reducer/index.ts
  client-config-app/src/services/stickers.ts
  client-config-app/src/services/teams.ts
  yarn.lock
Labels: Area:ClientConfigApp

#99 Fix build
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  .github/workflows/server.yml
  .github/workflows/web.yml
  client-config-app/src/App.tsx
  client-config-app/src/header/headerBtns.tsx
  client-config-app/src/list/UploadButton.tsx
  client-config-app/src/list/image-item.tsx
  client-config-app/src/list/index.tsx
  client-config-app/src/services/stickers.ts
  official-stickers/package.json
  package.json
  server.net/.vscode/launch.json
  server.net/Properties/launchSettings.json
  server.net/appsettings.Development.json
  server.net/appsettings.json
  stickers.code-workspace
  website/package.json
  website/src/components/compose/useMessages.tsx
  yarn.lock
Labels: Area:Pipelines

#102 Fe cd
  .github/workflows/fe-cd.yml
  manifest/package.json
  manifest/stickers/manifest.json
  manifest/stickers/zh-cn.json
Labels: Area:TeamsManifest, Area:Pipelines

#104 fix fe cd
  .github/workflows/fe-cd.yml
Labels: Area:Pipelines

#103 Carlos/backend infra
  server.net/.gitignore
  server.net/.vs/Stickers/DesignTimeBuild/.dtbcache.v2
  server.net/.vs/Stickers/FileContentIndex/ad979235-3e50-41cf-9b72-246e45cf47b2.vsidx
  server.net/.vs/Stickers/v17/.suo
  server.net/Controllers/StickersController.cs
  server.net/Entities/Sticker.cs
  server.net/Program.cs
  server.net/Service/StickerStorage.cs
Labels: Area:Server

#105 fix mv path
  .github/workflows/fe-cd.yml
Labels: Area:Pipelines

#118 add ci for azure functions and fix app cd
  .github/workflows/ci.yml
  client-config-app/package.json
Labels: Area:ClientConfigApp, Area:ImageFunctions, Area:Pipelines

#128 config WEBSITE MICROSOFT_APP_ID REACT_APP_API_ROOT
  .github/workflows/fe-cd.yml
Labels: Area:ClientConfigApp, Area:TeamsManifest, Area:Pipelines

#130 integration
  server.net/Bots/TeamsMessagingExtensionsBot.cs
  server.net/Bots/TeamsMessagingExtensionsBot.message.cs
  server.net/Bots/TeamsMessagingExtensionsBot.search.cs
  server.net/Cards/StickerCard.json
Labels: Area:Server

#129 try to fix server cd and ci
  .github/workflows/ci.yml
  .github/workflows/fe-cd.yml
  .github/workflows/server-cd.yml
  .gitignore
Labels: Area:Server, Area:Pipelines

#132 fix server CD
  .github/workflows/fe-cd.yml
  .github/workflows/server-cd.yml
Labels: Area:Pipelines

#133 fix server CD
  .github/workflows/fe-cd.yml
  .github/workflows/server-cd.yml
Labels: Area:Pipelines

#134 change upload
  client-config-app/src/header/headerBtns.tsx
  client-config-app/src/lib/http.ts
  client-config-app/src/list/UploadButton.tsx
  client-config-app/src/list/UploadImageItem.tsx
  client-config-app/src/list/UploadImageList.tsx
  client-config-app/src/list/image-item.tsx
  client-config-app/src/list/image-list.styles.tsx
  client-config-app/src/list/image-list.tsx
  client-config-app/src/services/stickers.ts
Labels: Area:ClientConfigApp

#136 Official stickers buld
  .github/workflows/ci.yml
  .github/workflows/fe-cd.yml
  .gitignore
  official-stickers/0001/01.png
  official-stickers/0001/02.png
  official-stickers/0001/03.png
  official-stickers/0001/04.png
  official-stickers/0001/05.png
  official-stickers/0001/06.png
  official-stickers/0001/07.png
  official-stickers/0001/08.png
  official-stickers/0001/09.png
  official-stickers/0001/10.png
  official-stickers/0001/11.png
  official-stickers/0001/12.png
  official-stickers/0001/13.png
  official-stickers/0001/14.png
  official-stickers/0001/15.png
  official-stickers/0001/16.png
  official-stickers/0001/17.png
  official-stickers/0001/18.png
  official-stickers/0001/19.png
  official-stickers/0001/20.png
  official-stickers/0001/21.png
  official-stickers/0001/22.png
  official-stickers/0001/23.png
  official-stickers/0001/24.png
  official-stickers/0001/index.json
  official-stickers/collection-name/index.json
  official-stickers/package.json
  official-stickers/scripts/build.mjs
Labels: Area:OfficialStickers, Area:Pipelines

#145 get sticker from tenant or user
  client-config-app/src/App.tsx
  client-config-app/src/header/headerBtns.tsx
  client-config-app/src/list/image-list.tsx
  client-config-app/src/list/index.tsx
  client-config-app/src/services/teams.ts
  manifest/.env
  manifest/stickers/manifest.json
Labels: Area:ClientConfigApp

#165 bot url and auth
  .gitignore
  StickersTests/Service/SesssionServiceTests.cs
  manifest/stickers/manifest.json
  server.net/Bots/TeamsMessagingExtensionsBot.cs
  server.net/Bots/TeamsMessagingExtensionsBot.message.cs
  server.net/Bots/TeamsMessagingExtensionsBot.search.cs
  server.net/Program.cs
  server.net/Resources/StickerStrings.resx
  server.net/Resources/StickerStrings.zh-CN.resx
  server.net/Service/SessionService.cs
Labels: Area:Server

#168 Update header
  client-config-app/src/App.tsx
  client-config-app/src/components/Header/Header.styles.ts
  client-config-app/src/components/Header/Header.tsx
  client-config-app/src/components/StickerApp.tsx
  client-config-app/src/components/header/headerBtns.tsx
  client-config-app/src/lib/http.ts
  client-config-app/src/lib/i18n.ts
  client-config-app/src/locales/en.json
  client-config-app/src/locales/index.ts
  client-config-app/src/locales/zh-cn.json
  client-config-app/src/services/stickers.ts
  client-config-app/src/services/teams.ts
  client-config-app/src/services/upload.ts
  client-config-app/src/utilities/teams.ts
  server.net/Controllers/StickersController.user.cs
  website/src/lib/i18n.ts
Labels: Area:ClientConfigApp, Area:Server

#170 fix delete and container
  client-config-app/package.json
  client-config-app/src/components/Alert/Alert.tsx
  client-config-app/src/components/Header/Header.tsx
  client-config-app/src/components/StickerApp.tsx
  client-config-app/src/lib/http.ts
  client-config-app/src/model/sticker.ts
  client-config-app/src/services/stickers.ts
  package.json
  server.net/Bots/TeamsMessagingExtensionsBot.cs
  server.net/Controllers/ControllerSession.cs
  server.net/Program.cs
  server.net/Service/BlobService.cs
  server.net/Service/DapperContext.cs
  server.net/Service/ENV.cs
  server.net/Stickers.csproj
  server.net/Utils/ConfigKeys.cs
  server.net/Utils/GlobalErrorHandling.cs
  server.net/appsettings.json
  website/package.json
  yarn.lock
Labels: Area:ClientConfigApp, Area:Server

#172 fix edit
  client-config-app/src/App.tsx
  client-config-app/src/components/ImageItem/ImageItem.tsx
  client-config-app/src/components/ImageItem/UploadImageItem.tsx
  client-config-app/src/components/ImageList/ImageList.tsx
  client-config-app/src/components/ImageList/index.tsx
  client-config-app/src/components/StickerApp.tsx
  client-config-app/src/hooks/useStickersList.ts
  client-config-app/src/services/stickers.ts
  client-config-app/src/services/teams.ts
  server.net/Service/StickerStorage.cs
  server.net/Stickers.csproj
Labels: Area:ClientConfigApp, Area:Server

#177 database cache and tenant op
  server.net/Bots/TeamsMessagingExtensionsBot.cs
  server.net/Bots/TeamsMessagingExtensionsBot.message.cs
  server.net/Bots/TeamsMessagingExtensionsBot.search.cs
  server.net/Controllers/StickersController.admin.cs
  server.net/Controllers/StickersController.user.cs
  server.net/Entities/Sticker.cs
  server.net/Program.cs
  server.net/Service/StickerDatabase.cs
  server.net/Service/StickerService.cs
  server.net/Service/StickerStorage.cs
Labels: Area:Server

#178 Add sql
  server.net/sql/stickers.sql
Labels: Area:Server

#176 Vinfol/add admin sso
  .github/workflows/fe-cd.yml
  client-config-app/.env.development
  client-config-app/.env.production
  client-config-app/package.json
  client-config-app/src/assets/LoginPagePic.png
  client-config-app/src/components/Header/Header.tsx
  client-config-app/src/components/ImageItem/UploadImageItem.tsx
  client-config-app/src/components/ImageList/ImageList.tsx
  client-config-app/src/components/ImageList/TenantImageList.tsx
  client-config-app/src/components/ImageList/UserImageList.tsx
  client-config-app/src/components/StickerApp.tsx
  client-config-app/src/components/WelcomePage/WelcomePage.styles.ts
  client-config-app/src/components/WelcomePage/WelcomePage.tsx
  client-config-app/src/hooks/useStickersList.ts
  client-config-app/src/lib/http.ts
  client-config-app/src/locales/en.json
  client-config-app/src/locales/index.ts
  client-config-app/src/locales/zh-cn.json
  client-config-app/src/services/stickers.ts
  client-config-app/src/services/upload.ts
  client-config-app/src/utilities/RoleUtils.tsx
  manifest/.env
  manifest/.env.development
  manifest/stickers/manifest.json
  yarn.lock
Labels: Area:ClientConfigApp

#179 add admin upload controller
  client-config-app/src/services/upload.ts
  server.net/Controllers/StickersController.admin.cs
  server.net/Controllers/StickersController.user.cs
  server.net/Controllers/UploadController.cs
  server.net/Models/UploadRequest.cs
  server.net/Service/BlobService.cs
Labels: Area:Server

#180 change upload api
  client-config-app/src/services/stickers.ts
  client-config-app/src/services/upload.ts
Labels: Area:ClientConfigApp

#195 fix admin auth in backend
  StickersTests/StickersTests.csproj
  client-config-app/src/components/ImageList/TenantImageList.tsx
  client-config-app/src/components/LoginPage/LoginPage.styles.ts
  client-config-app/src/components/LoginPage/LoginPage.tsx
  client-config-app/src/hooks/useStickersList.ts
  client-config-app/src/lib/env.ts
  client-config-app/src/locales/en.json
  client-config-app/src/locales/zh-cn.json
  manifest/stickers/manifest.json
  server.net/Controllers/ControllerSession.cs
  server.net/Controllers/StickersController.admin.cs
  server.net/Controllers/StickersController.user.cs
  server.net/Program.cs
  yarn.lock
Labels: Area:Server
